### PR TITLE
feat: add support for install deps for pnpm

### PR DESCRIPTION
**Pull request by pjvds**

### CODE REVIEW

**Comment by pjvds** [comment]
Anything that can be done to speed up the pull of this one?

**Comment by pjvds** [comment]
Let me know if there is anything that I can do to make this PR be pulled.

**Comment by claughinghouse** [comment]
> Let me know if there is anything that I can do to make this PR be pulled.

I ended up forking and publishing my own action. I went a different route on my deployment strategy and deleted the action from the marketplace. If it helps, this is my deployment action:

```
name: Deploy PR previews to Development

on:
  # push:
  #   branches:
  #     - !main
  # pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Build and Deploy pr-${{ github.event.pull_request.number }} to Development"
    environment:
      # name: development
      # url: "${{ steps.extract-url.outputs.URL }}"
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.local/share/pnpm/store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: 7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ARN_AWS_IAM_DEVELOPMENT }}
          aws-region: us-east-2

      - name: Deploy PR ${{ github.event.pull_request.number }} to AWS Development
        run: |
          pnpm sst deploy --stage pr-${{ github.event.pull_request.number }}

      - name: "Retreive Deployment URL"
        id: extract-url
        run: |
          echo "URL=$(jq -r '..? | .URL | select( . != null )' .sst/outputs.json)" >> $GITHUB_OUTPUT
```

**Comment by quenginedev** [comment]
Everything looks good 👍🏼

**Pull request merged**
